before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- binary: local-chart-version

  ldflags: -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  
  env:
  - CGO_ENABLED=0

  goos:
    - linux
    - darwin

  goarch:
    - amd64

archives:
- name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  files:
    - plugin.yaml
    - ./docs/**

  format: tar.gz
  replacements:
    386: i386

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

env_files:
  github_token: ~/.github/helm-local-chart-version.token
