# Build customization
builds:
  - binary: local-chart-version

    ldflags: -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin

    goarch:
      - amd64

# Archive customization
archive: 
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  files:
    - plugin.yaml
    - README.md
    - ./docs/**

  format: tar.gz

env_files:
  github_token: ~/.github/helm-local-chart-version.token